apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-db
  namespace: <namespace>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-db
  template:
    metadata:
      labels:
        app: oracle-db
    spec:
      containers:
      - name: oracle-db
        image: container-registry.oracle.com/database/enterprise:19.3.0.0
        ports:
        - containerPort: 1521
        - containerPort: 5500
      imagePullSecrets:
      - name: oracle-registry-secret
